### ISSUE TITLE
Pass function callback as props to scenes

### ISSUE THREAD

**Issue by emerson233** [grahammendick/navigation#322]
Hello, it's me again.
One question, how do we pass function type props to scenes?
I am doing something like this:
```javascript
const stateNavigator = new StateNavigator([
  {key: 'sceneA', trackCrumbTrail: true},
  {key: 'sceneB', trackCrumbTrail: true},
]);
const {sceneA, sceneB} = stateNavigator.states;
sceneA.renderScene = () => <Foo />;
sceneB.renderScene = ({callback}) => <Bar />;

stateNavigator.navigate("sceneB", {
  callback: () => {
    // change something
  }
})
```
However, the value for `callback` in `sceneB.renderScene` is undefined.
It seems function type variable is erased from `navigationData` when encoding data to routeInfo and decoding it back from routeInfo?

**Comment by grahammendick** [comment]
Hey, great to hear from you again. You can't pass functions in navigation data. If you let me know your use-case then I'll try and help out

**Comment by emerson233** [comment]
The navigation library([react-native-navigation](https://github.com/wix/react-native-navigation)) we used before can pass function call to its "screens". I am planning to build a feature similar to [this one](https://github.com/wix/react-native-navigation/blob/master/lib/src/components/Store.ts) for backward compatibility.
Please let me know If you have a better idea.

**Comment by grahammendick** [comment]
Let me see if I understand what you're trying to do. If you navigate from A --> B --> C then you want to update B's navigation data when you're on C. Is that right?

**Comment by emerson233** [comment]
Yes, do you have any advice for this scenario?

**Comment by grahammendick** [comment]
Yes, you can do that using fluent navigation. Let's say that when you first navigated from A to B you passed 'x' with a value of 1 in navigation data
```js
// On Scene A
stateNavigator.navigate('B', {x: 1});
``` 
Now, you're on C and you want to change the `x` navigation data to 2 on scene B.
```js
// On Scene C
var link = stateNavigator.fluent(true)
  .navigateBack(2)
  .navigate('B', {x: 2})
  .navigate('A').url;
stateNavigator.navigateLink(url|);
```
You see, fluent navigation lets you perform multiple navigations at once. Here we're navigating back 2 scenes to A, then navigating forward to B and passing the new value for x, then navigating forward to A again. The Navigation router only applies these navigations when you call `navigateLink`. It applies these changes in the most efficient way possible. So the user won't see any changes until they tap the back button.

**Comment by grahammendick** [comment]
Sorry, I made a mistake in the fluent navigation code sample. I've corrected it, so please give it a reread

**Comment by emerson233** [comment]
Seems promising, but still not flexible enough compared to passing callback.

Consider this scenario: In scene B, user click a button navigating to scene C. If scene C is displaying a dialog which contains two button for user to click(cancel/confirm). After user clicks one of them, we do as following:
```javascript
// On Scene C
var link = stateNavigator.fluent(true)
  .navigateBack(2)
  .navigate('B', {clickedButtonIndex: 0});
stateNavigator.navigateLink(url|);
```
And user navigateBack to scene B now. Then user click another button navigating to scene D, which is the same component as scene C. If user clicks cancel/confirm button in scene D, then we have to figure out where is this click event from (try not to mess up with scene C).

**Comment by grahammendick** [comment]
I'm confused. Can you explain what you can do with the callback that you don't think you can do with fluent navigation, please?

**Comment by emerson233** [comment]
Sorry, since I am not a native english speaker, it's hard to make myself clear.
Fluent navigation is capable of doing everything as you said, but it's making codebase complicated and hard to understand.

**Comment by grahammendick** [comment]
I wouldn't use fluent navigation to tell screen B that you clicked a button on screen C. You should only use fluent navigation to change navigation data.

If you want to tell screen B that you clicked a button then you should use React context. React context is the way to communicate and pass data between scenes.

**Comment by emerson233** [comment]
Understood. Thanks for your explaining.

**Comment by grahammendick** [comment]
No problem. Thanks for the question.

You couldn't use React Context with react-native-navigation because each scene is mounted under a different React root element. 

You can use React Context with the Navigation router because all scenes share a common React root element.

**Comment by studyroz** [comment]
IMO, being able to pass function as data helps to increase flexibility.

Consider a selectable user list scene, which may be used in many places in an app.

~~~javascript
stateNavigator.navigate('users-selector', {
  title: "Contacts",
  fetchData: () => {
    // Fetch from contacts
  },
  renderListItem: (user) => {
    // Render a contact list item
  },
  onSelected: (users) => {
  }
})

// Another place:
stateNavigator.navigate('users-selector', {
  title: "Team Members",
  fetchData: () => {
    // Fetch from team members
  },
  renderListItem: (user) => {
    // Render a member list item
  },
  onSelected: (users) => {
  }
})
~~~

The 'users-selector' scene handles selection state management, template header & bottom components rendering and so on. By passing custom action as function through data, we can make `users-selector` scene very flexible.

**Comment by grahammendick** [comment]
Hey @studyroz It's better to do things like that with React than with the Navigation router. For example, you can wrap the `UserSelector` component in two different Higher Order Components like `Contacts` and `TeamMembers` components. Then you can pass a `renderListItem` prop to he `UserSelector` component

**Comment by mpiannucci** [comment]
@grahammendick I disagree. Its a really simple pattern that is way clearer than having to wrap everything in a context/ HOC. I'm not talking about the callbacks for fetching data but moreso the ones @studyroz defined for `onSelected`. That's a pattern I would use a lot for a settings screen for instance. 

I would argue that this hurts reusability too because as I understand it you cant have props that are callbacks when using a screen?

**Comment by grahammendick** [comment]
@mpiannucci Sounds like you’re looking for a convenient way to pass data back from Scene B to Scene A, right? I’ll try and explain why I don’t think that’s a good idea. I’ll use Hooks because it makes the problem more obvious. Here’s Scene A. It displays a count and has a button that navigates to Scene B. When it navigates to Scene B it passes a callback that adds 1 to the count.
```jsx
const SceneA = () => {
  const {count, setCount} = useState(0)
  const {stateNavigator} = useContext(NavigationContext);
  const add = () => setCount(count + 1)
  return (
    <>
      <Text>{count}</Text>
      <Button onPress={() => stateNavigator.navigate('sceneB', { add }) />
    </>	
  )
}
```
Let’s say that Scene B calls the `add` callback twice in a row. The count should now be 2, but when you navigate back to Scene A the count is actually only 1. That’s because the `add` callback on Scene B closed over the count when it was 0. When Scene B calls `add` the first time, the `add` callback is recreated in Scene A and closes over the new count of 1. But Scene B still has the old value for the `add` callback which closed over the count when it was 0. So when Scene B calls `add` a second time it sets a value of 1.

**Comment by mpiannucci** [comment]
Aha good call. Thanks for the explanation. Some of this is new to me coming from c++ and swift where the flow is a little different

**Comment by mpiannucci** [comment]
So I am hitting this again. I am trying to display a modal screen where a user can select an item, the modal is dismissed, and then that item is presented in the main view. I forgot this wasn't possible and was going crazy trying to figure out why the callback wasn't working. 

Is there any technical limitation to why passing callbacks isn't supported? I know the case with setting the count and such but my flow deals with strings so i am strictly trying to present a one off select and then closing the dialog. 

I want the native search bar functionality, otherwise i wouldn't give the modal its own navigation context.

**Comment by grahammendick** [comment]
You don’t have to use context. You can pass the function as a prop.
```jsx
const [val, setVal] = useState(null);
const modalNavigator = useMemo(() => {
  const navigator = new StateNavigator([
    {key: ‘search’}
  ]);
  const {search} = navigator.states;
  search.renderScene = () => <Search setVal={setVal} />
  navigator.navigate('search');
  return navigator;
}, [setVal]);
return (
  <Modal>
    <NavigationHandler stateNavigator={modalNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </Modal>
);
```

**Comment by mpiannucci** [comment]
So you can pass a function as long as you pass it to render scene. Great thanks for the help!!!!!

**Comment by grahammendick** [comment]
Here’s a more complete example of how you can use props, instead of context, to pass data from a parent scene to a modal scene (make sure you’re using the just published `navigation-react-native` v8.7.1)

```jsx
const Wrapper = ({state, ...props}) => state.renderScene(props);

const ParentScene = () => {
  const [val, setVal] = useState();
  const modalNavigator = useMemo(() => {
    const navigator = new StateNavigator([{key: 'scene'}])
    const {scene} = stateNavigator.states;
    screen.renderScene = (props) => <ModalScene {...props} />;
    navigator.navigate('scene');
    return navigator;
  });

  return (
    <NavigationHandler stateNavigator={modalNavigator}>
      <NavigationStack renderScene={(state) => (
        <Wrapper state={state} val={val} setVal={setVal} />
      )} />
    </NavigationHandler>
  );
}
```
